In [15]:
import numpy as np

test_inputs = \
    """0,9 -> 5,9
8,0 -> 0,8
9,4 -> 3,4
2,2 -> 2,1
7,0 -> 7,4
6,4 -> 2,0
0,9 -> 2,9
3,4 -> 1,4
0,0 -> 8,8
5,5 -> 8,2"""

input = test_inputs
use_test = True
if use_test:
    input = test_inputs

input_lines = input.splitlines()

input = [coord.split("->") for coord in input_lines]
input = [[x[0].split(","), x[1].split(",")] for x in input]

input = np.array(input).astype(int)
max_dim = input.max()
hit_map = np.zeros((max_dim, max_dim))

print(input.shape)
print(input)


(10, 2, 2)
[[[0 9]
  [5 9]]

 [[8 0]
  [0 8]]

 [[9 4]
  [3 4]]

 [[2 2]
  [2 1]]

 [[7 0]
  [7 4]]

 [[6 4]
  [2 0]]

 [[0 9]
  [2 9]]

 [[3 4]
  [1 4]]

 [[0 0]
  [8 8]]

 [[5 5]
  [8 2]]]


In [24]:
# Filter out only Vertical and Horizontal lines
horiz_inputs = (input[:,0,0] == input[:,1,0]) | (input[:,0,1] == input[:])

# List of first coordinate:   input[:,0,:])
# List of second coordinates: input[:,1,:])

vert_inputs = (input[:,1,0] == input[:,1,1])
print(horiz_inputs)
print(vert_inputs)


# Apply lines to hit_map (+1 per hit)


# Count number of places that there are two or more hits

[False False False  True  True False False False False False]
[False False False False False False False False  True False]


/tmp/ipykernel_15475/315276578.py:2: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  horiz_inputs = (input[:,0,0] == input[:,1,0]) | (input[:,0,1] == input[:])
